### ISSUE TITLE
Fixing author names in AntCat

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy/antcat#41]
Found an error while fixing author names in AntCat: the deleting button is not working.

Background: the best solution for some author aliases is deletion instead of merging names. 
Exemple: Fisher, B. L.  and Fisher B. L. 
Problem: There is a delete button, and it seems to work. However, in the end of the list I was fixing, I realized that the name I just deleted was still there. 

So, it would be good to search again for name inconsistencies -- I am pretty sure some of my deletions are still there (all of them were names with no space between abbreviations.

**Comment by flaviaesteves** [comment]
I also received a bug message when trying to fix one of the names: "Brown R. L."
I was trying to insert a comma between surname and name abbreviation, but AntCat prevented me to do that.

**Comment by foozleface** [comment]
Could you send me a the URL that you were working on at the time? 

And you were trying to transform “Brown R. L.” into “Brown, R. L.”, correct?

**Comment by foozleface** [comment]
Okay, I can repro these now, disregard previous messages. This is in 
http://localhost:3000/authors/11282/edit

  The error is thrown because Brown, R. L. already exists as a name. Instead, this should pop up a proper error.

   We also need a "delete" ability for authors. We currently have a broken delete button for references.

I'm going to close this issue and add three more:

1) http://localhost:3000/authors/11282/edit - display a good error for this case:
ActiveRecord::RecordInvalid (Validation failed: Name has already been taken):
  app/controllers/author_names_controller.rb:9:in `update'
  config/initializers/quiet_assets.rb:8:in `call_with_quiet_assets'

2) Add delete feature for authors

3) Fix delete for references.

**Comment by foozleface** [comment]
Ahh, there is a "delete" for sub-item #2. If you edit and then highlight the name, it is presented (yay, that's totally intuitive). 
However, it silently errors out:

Started DELETE "/authors/11282/author_names/194557" for 127.0.0.1 at 2015-09-02 12:39:29 -0700

AbstractController::ActionNotFound (The action 'destroy' could not be found for AuthorNamesController):
  config/initializers/quiet_assets.rb:8:in `call_with_quiet_assets'.

**Comment by foozleface** [comment]
Fixed, comitted, pushed. It's now live on the site. 

  The error popup is replaced with a warning that you can't create a name if it already exists, and delete works.

**Comment by foozleface** [comment]
name
"Bolton B."
"Brown R. L."
"Eder J."
"Escalante G., J. A."
"Kitahiro S."
"Kubik E."
"Ma L."
"Rembold H."
"Xenarios I."

**Comment by flaviaesteves** [comment]
Thanks Joe!

On Thu, Sep 3, 2015 at 10:19 PM, foozleface <notifications@github.com>
wrote:

> name
> "Bolton B."
> "Brown R. L."
> "Eder J."
> "Escalante G., J. A."
> "Kitahiro S."
> "Kubik E."
> "Ma L."
> "Rembold H."
> "Xenarios I."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy/antcat/issues/41#issuecomment-137650809>.
>



-- 
Flávia Esteves

Postdoctoral Fellow
Entomology
California Academy of Sciences
Golden Gate Park
55 Music Concourse Drive
San Francisco, CA 94118, U.S.A.
